### ISSUE TITLE
merge media queries

### ISSUE THREAD

**Issue by ronaldruzicka** [actum/gulp-dev-stack#151]
Should we add a media query merge tool to group together styles that are under the same media query?
e.g: 
```css 
.foo {
  width: 240px;
}

@media screen and (min-width: 768px) {
  .foo {
    width: 576px;
  }
}

.bar {
  width: 160px;
}

@media screen and (min-width: 768px) {
  .bar {
    width: 384px;
  }
}
```

would result to: 
```css
.foo {
  width: 240px;
}

.bar {
  width: 160px;
}

@media screen and (min-width: 768px) {
  .foo {
    width: 576px;
  }
  .bar {
    width: 384px;
  }
}
```
I know about the [mqpacker](https://github.com/hail2u/node-css-mqpacker)

**Comment by janpanschab** [comment]
Would be nice to have results from some real projects. Please, test it on 2 or 3 current projects. Test the size and also problem with specificity (order).

**Comment by kettanaito** [comment]
How do you think it would work if we do something like:
```css
.foo {
    position: relative;
    margin-top: 10px;
    
    @media screen and (max-width: 500px) {
        margin-top: 5px;
    }
}
```
Do we forbid this kind of usage as a part of CSS quality assurance? For me it makes sense in cases certain media query should add up some properties.
